//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP123_Programming2_Assignment06.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMP123_Programming2_Assignment06.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string CalculateButtonStringEnglish {
            get {
                return ResourceManager.GetString("CalculateButtonStringEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer.
        /// </summary>
        internal static string CalculateButtonStringFrench {
            get {
                return ResourceManager.GetString("CalculateButtonStringFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID:.
        /// </summary>
        internal static string EmployeeIDLabelEnglish {
            get {
                return ResourceManager.GetString("EmployeeIDLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employé Idaho:.
        /// </summary>
        internal static string EmployeeIDLabelFrench {
            get {
                return ResourceManager.GetString("EmployeeIDLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Name.
        /// </summary>
        internal static string EmployeeNameLabelEnglish {
            get {
                return ResourceManager.GetString("EmployeeNameLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;employé.
        /// </summary>
        internal static string EmployeeNameLabelFrench {
            get {
                return ResourceManager.GetString("EmployeeNameLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishRadioButtonEnglish {
            get {
                return ResourceManager.GetString("EnglishRadioButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        internal static string EnglishRadioButtonFrench {
            get {
                return ResourceManager.GetString("EnglishRadioButtonFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FrenchRadioButtonEnglish {
            get {
                return ResourceManager.GetString("FrenchRadioButtonEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string FrenchRadioButtonFrench {
            get {
                return ResourceManager.GetString("FrenchRadioButtonFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string GroupBoxEnglish {
            get {
                return ResourceManager.GetString("GroupBoxEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string GroupBoxFrench {
            get {
                return ResourceManager.GetString("GroupBoxFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Worked:.
        /// </summary>
        internal static string HoursWorkedLabelEnglish {
            get {
                return ResourceManager.GetString("HoursWorkedLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures travaillées:.
        /// </summary>
        internal static string HoursWorkedLabelFrench {
            get {
                return ResourceManager.GetString("HoursWorkedLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MailOrderCompanyBonusImprove {
            get {
                object obj = ResourceManager.GetObject("MailOrderCompanyBonusImprove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButtonStringEnglish {
            get {
                return ResourceManager.GetString("NextButtonStringEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        internal static string NextButtonStringFrench {
            get {
                return ResourceManager.GetString("NextButtonStringFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintButtonStringEnglish {
            get {
                return ResourceManager.GetString("PrintButtonStringEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        internal static string PrintButtonStringFrench {
            get {
                return ResourceManager.GetString("PrintButtonStringFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Bonus:.
        /// </summary>
        internal static string SalesBonusLabelEnglish {
            get {
                return ResourceManager.GetString("SalesBonusLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boni de vente:.
        /// </summary>
        internal static string SalesBonusLabelFrench {
            get {
                return ResourceManager.GetString("SalesBonusLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Bonus:.
        /// </summary>
        internal static string TitleBarStringEnglish {
            get {
                return ResourceManager.GetString("TitleBarStringEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boni de vente:.
        /// </summary>
        internal static string TitleBarStringFrench {
            get {
                return ResourceManager.GetString("TitleBarStringFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales:.
        /// </summary>
        internal static string TotalSalesLabelEnglish {
            get {
                return ResourceManager.GetString("TotalSalesLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total des ventes:.
        /// </summary>
        internal static string TotalSalesLabelFrench {
            get {
                return ResourceManager.GetString("TotalSalesLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap waring_icon {
            get {
                object obj = ResourceManager.GetObject("waring_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon waring_icon1 {
            get {
                object obj = ResourceManager.GetObject("waring_icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
